/**********************************************************************
*
*   Component generated by Quest
*
*   WARNING: By editing this component by hand, you will lose the ability to regenerate the code without conflicts. 
*   To preseve that abilty, always export from Quest to regenerate this file.
*   To setup props, bindings and actions, use the Quest editor
*   Code Logic goes in the hook associated with this component
*
*   For help and further details refer to: https://www.quest.ai/docs
*
*
**********************************************************************/

import { Helmet } from 'react-helmet';
import Tempura3DIllustratioImage from 'src/assets/images/Swap_Tempura_3D_Illustration.png';
import Graph1Image from 'src/assets/images/Swap_Graph.png';
import VectorImage from 'src/assets/images/Swap_Vector_3.png';
import Vector1Image from 'src/assets/images/Swap_Vector_2.png';
import Image93Image from 'src/assets/images/Swap_image_93.png';
import Vector2Image from 'src/assets/images/Swap_Vector_1.png';
import Vector3Image from 'src/assets/images/Swap_Vector.png';
import SubtractImage from 'src/assets/images/Swap_Subtract_1.png';
import Subtract1Image from 'src/assets/images/Swap_Subtract.png';
import { styled } from '@mui/material/styles';
import Token from 'src/components/Token/Token';
import Footer from 'src/components/Footer/Footer';
import TopNavigation from 'src/components/TopNavigation/TopNavigation';
import Ellipse2Image from 'src/assets/images/TopNavigation_Ellipse_2_1.png';
 
const Swap1 = styled("div")({  
  backgroundColor: `rgba(255, 255, 255, 1)`,  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  width: "100%",  
  height: `946.41px`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
});
  
const Frame7675 = styled("div")({  
  background: `linear-gradient(180deg, rgba(255, 26, 29, 1) -3.0616171314629196e-15%, rgba(232, 85, 87, 1) 99.99999999999999%)`,  
  display: `flex`,  
  position: `absolute`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `space-between`,  
  alignItems: `center`,  
  padding: `19px 160px`,  
  boxSizing: `border-box`,  
  width: `1920px`,  
  height: `120px`,  
  left: `0px`,  
  top: `68px`,  
  overflow: `hidden`,  
});
  
const Trade = styled("div")({  
  textAlign: `left`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(255, 255, 255, 1)`,  
  fontStyle: `normal`,  
  fontWeight: `700`,  
  fontSize: `48px`,  
  letterSpacing: `0px`,  
  textDecoration: `none`,  
  lineHeight: `24px`,  
  textTransform: `none`,  
});
  
const Tempura3DIllustratio = styled("img")({  
  height: `450px`,  
  width: `450px`,  
  objectFit: `cover`,  
});
  
const Section4 = styled("div")({  
  background: `linear-gradient(180deg, rgba(255, 193, 119, 1) 2.685613743960854%, rgba(255, 236, 214, 1) 70.22814154624938%)`,  
  display: `flex`,  
  position: `absolute`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `space-between`,  
  alignItems: `flex-start`,  
  padding: `72px 160px`,  
  boxSizing: `border-box`,  
  width: `1920px`,  
  left: `0px`,  
  top: `190px`,  
});
  
const Graph = styled("div")(({ theme }) =>({  
  backgroundColor: `rgba(246, 246, 246, 1)`,  
  boxShadow: `0px 4px 16px rgba(0, 0, 0, 0.15)`,  
  borderRadius: `32px`,  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  width: `819px`,  
  height: `304px`,  
}));
  
const Group1004 = styled("div")({  
  display: `flex`,  
  position: `absolute`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  width: `779px`,  
  height: `40px`,  
  left: `21px`,  
  top: `18px`,  
});
  
const Group1012 = styled("div")({  
  display: `flex`,  
  position: `absolute`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  width: `779px`,  
  height: `40px`,  
  left: `0px`,  
  top: `0px`,  
});
  
const Q7210UsdcBnto0824135Span1 = styled("span")({  
  whiteSpace: `pre-wrap`,  
  color: `rgba(0, 0, 0, 1)`,  
  fontStyle: `normal`,  
  fontWeight: `800`,  
  fontSize: `32px`,  
  letterSpacing: `0px`,  
  textDecoration: `none`,  
  lineHeight: `40px`,  
  textTransform: `none`,  
});
  
const Q7210UsdcBnto0824135Span2 = styled("span")({  
  whiteSpace: `pre-wrap`,  
  color: `rgba(0, 0, 0, 1)`,  
  fontStyle: `normal`,  
  fontWeight: `800`,  
  fontSize: `16px`,  
  letterSpacing: `0px`,  
  textDecoration: `none`,  
  lineHeight: `40px`,  
  textTransform: `none`,  
});
  
const Q7210UsdcBnto0824135Span3 = styled("span")({  
  whiteSpace: `pre-wrap`,  
  color: `rgba(27, 190, 0, 1)`,  
  fontStyle: `normal`,  
  fontWeight: `800`,  
  fontSize: `16px`,  
  letterSpacing: `0px`,  
  textDecoration: `none`,  
  lineHeight: `40px`,  
  textTransform: `none`,  
});
  
const Q7210UsdcBnto0824135 = styled("div")({  
  textAlign: `left`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(0, 0, 0, 1)`,  
  fontStyle: `normal`,  
  fontWeight: `800`,  
  fontSize: `nullpx`,  
  letterSpacing: `0px`,  
  textDecoration: `none`,  
  lineHeight: `40px`,  
  textTransform: `none`,  
  position: `absolute`,  
  left: `0px`,  
  top: `0px`,  
});
  
const Frame7674 = styled("div")({  
  backgroundColor: `rgba(217, 217, 217, 1)`,  
  borderRadius: `8px`,  
  display: `flex`,  
  position: `absolute`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `center`,  
  alignItems: `center`,  
  padding: `6px 28px`,  
  boxSizing: `border-box`,  
  width: `227px`,  
  height: `24px`,  
  left: `552px`,  
  top: `8px`,  
});
  
const Group1000 = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  width: `43px`,  
  height: `20px`,  
  margin: `0px`,  
});
  
const Rectangle7 = styled("div")(({ theme }) =>({  
  backgroundColor: `rgba(255, 153, 34, 1)`,  
  borderRadius: `64px`,  
  width: `43px`,  
  height: `18px`,  
  position: `absolute`,  
  left: `0px`,  
  top: `1px`,  
}));
  
const ButtonTitle = styled("div")(({ theme }) =>({  
  textAlign: `center`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(255, 255, 255, 1)`,  
  fontStyle: `normal`,  
  fontWeight: `700`,  
  fontSize: `12px`,  
  letterSpacing: `0px`,  
  textDecoration: `none`,  
  lineHeight: `20px`,  
  textTransform: `none`,  
  position: `absolute`,  
  left: `9px`,  
  top: `0px`,  
}));
  
const Group1001 = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  width: `43px`,  
  height: `20px`,  
  margin: `0px 0px 0px 16px`,  
});
  
const Rectangle71 = styled("div")({  
  backgroundColor: `rgba(255, 153, 34, 0)`,  
  borderRadius: `64px`,  
  width: `43px`,  
  height: `18px`,  
  position: `absolute`,  
  left: `0px`,  
  top: `1px`,  
});
  
const ButtonTitle1 = styled("div")(({ theme }) =>({  
  textAlign: `center`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(134, 134, 134, 1)`,  
  fontStyle: `normal`,  
  fontWeight: `700`,  
  fontSize: `12px`,  
  letterSpacing: `0px`,  
  textDecoration: `none`,  
  lineHeight: `20px`,  
  textTransform: `none`,  
  position: `absolute`,  
  left: `12px`,  
  top: `0px`,  
}));
  
const Group1002 = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  width: `43px`,  
  height: `20px`,  
  margin: `0px 0px 0px 16px`,  
});
  
const Rectangle72 = styled("div")({  
  backgroundColor: `rgba(255, 153, 34, 0)`,  
  borderRadius: `64px`,  
  width: `43px`,  
  height: `18px`,  
  position: `absolute`,  
  left: `0px`,  
  top: `1px`,  
});
  
const ButtonTitle2 = styled("div")(({ theme }) =>({  
  textAlign: `center`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(134, 134, 134, 1)`,  
  fontStyle: `normal`,   
  fontWeight: `700`,  
  fontSize: `12px`,  
  letterSpacing: `0px`,  
  textDecoration: `none`,  
  lineHeight: `20px`,  
  textTransform: `none`,  
  position: `absolute`,  
  left: `13px`,  
  top: `0px`,  
}));
  
const Group1003 = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  width: `43px`,  
  height: `20px`,  
  margin: `0px 0px 0px 16px`,  
});
  
const Rectangle73 = styled("div")({  
  backgroundColor: `rgba(255, 153, 34, 0)`,  
  borderRadius: `64px`,  
  width: `43px`,  
  height: `18px`,  
  position: `absolute`,  
  left: `0px`,  
  top: `1px`,  
});
  
const ButtonTitle3 = styled("div")(({ theme }) =>({  
  textAlign: `center`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(134, 134, 134, 1)`,  
  fontStyle: `normal`,  
  fontWeight: `700`,  
  fontSize: `12px`,  
  letterSpacing: `0px`,  
  textDecoration: `none`,  
  lineHeight: `20px`,  
  textTransform: `none`,  
  position: `absolute`,  
  left: `14px`,  
  top: `0px`,  
}));
  
const Group1014 = styled("div")({  
  display: `flex`,  
  position: `absolute`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  width: `780px`,  
  height: `227px`,  
  left: `20px`,  
  top: `58px`,  
});
  
const Group1013 = styled("div")({  
  display: `flex`,  
  position: `absolute`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  width: `779px`,  
  height: `227px`,  
  left: `0px`,  
  top: `0px`,  
});
  
const Q1900 = styled("div")({  
  textAlign: `center`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(147, 147, 147, 1)`,  
  fontStyle: `normal`,   
  fontWeight: `700`,  
  fontSize: `10px`,  
  letterSpacing: `0px`,  
  textDecoration: `none`,  
  lineHeight: `20px`,  
  textTransform: `none`,  
  position: `absolute`,  
  left: `0px`,  
  top: `207px`,  
});
  
const Q2000 = styled("div")({  
  textAlign: `center`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(147, 147, 147, 1)`,  
  fontStyle: `normal`,   
  fontWeight: `700`,  
  fontSize: `10px`,  
  letterSpacing: `0px`,  
  textDecoration: `none`,  
  lineHeight: `20px`,  
  textTransform: `none`,  
  position: `absolute`,  
  left: `106px`,  
  top: `207px`,  
});
  
const Graph1 = styled("img")({  
  height: `199px`,  
  width: `779px`,  
  position: `absolute`,  
  left: `1558px`,  
  top: `199px`,  
});
  
const Q2100 = styled("div")({  
  textAlign: `center`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(147, 147, 147, 1)`,  
  fontStyle: `normal`,  
  fontWeight: `700`,  
  fontSize: `10px`,  
  letterSpacing: `0px`,  
  textDecoration: `none`,  
  lineHeight: `20px`,  
  textTransform: `none`,  
  position: `absolute`,  
  left: `213px`,  
  top: `207px`,  
});
  
const Q2200 = styled("div")({  
  textAlign: `center`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(147, 147, 147, 1)`,  
  fontStyle: `normal`,   
  fontWeight: `700`,  
  fontSize: `10px`,  
  letterSpacing: `0px`,  
  textDecoration: `none`,  
  lineHeight: `20px`,  
  textTransform: `none`,  
  position: `absolute`,  
  left: `318px`,  
  top: `207px`,  
});
  
const Q2300 = styled("div")({  
  textAlign: `center`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(147, 147, 147, 1)`,  
  fontStyle: `normal`,  
  fontWeight: `700`,  
  fontSize: `10px`,  
  letterSpacing: `0px`,  
  textDecoration: `none`,  
  lineHeight: `20px`,  
  textTransform: `none`,  
  position: `absolute`,  
  left: `425px`,  
  top: `207px`,  
});
  
const Q0000 = styled("div")({  
  textAlign: `center`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(147, 147, 147, 1)`,  
  fontStyle: `normal`,  
  fontWeight: `700`,  
  fontSize: `10px`,  
  letterSpacing: `0px`,  
  textDecoration: `none`,  
  lineHeight: `20px`,  
  textTransform: `none`,  
  position: `absolute`,  
  left: `532px`,  
  top: `207px`,  
});
  
const Q0100 = styled("div")({  
  textAlign: `center`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(147, 147, 147, 1)`,  
  fontStyle: `normal`,  

  fontWeight: `700`,  
  fontSize: `10px`,  
  letterSpacing: `0px`,  
  textDecoration: `none`,  
  lineHeight: `20px`,  
  textTransform: `none`,  
  position: `absolute`,  
  left: `640px`,  
  top: `207px`,  
});
  
const Q0200 = styled("div")({  
  textAlign: `center`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(147, 147, 147, 1)`,  
  fontStyle: `normal`,  

  fontWeight: `700`,  
  fontSize: `10px`,  
  letterSpacing: `0px`,  
  textDecoration: `none`,  
  lineHeight: `20px`,  
  textTransform: `none`,  
  position: `absolute`,  
  left: `746px`,  
  top: `207px`,  
});
  
const Oct1520220834Pm = styled("div")({  
  textAlign: `left`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(128, 128, 128, 1)`,  
  fontStyle: `normal`,   
  fontWeight: `500`,  
  fontSize: `12px`,  
  letterSpacing: `0px`,  
  textDecoration: `none`,  
  lineHeight: `40px`,  
  textTransform: `none`,  
  width: `129px`,  
  height: `14px`,  
  position: `absolute`,  
  left: `651px`,  
  top: `0px`,  
});
  
const TempuraSwapMain = styled("div")(({ theme }) =>({  
  backgroundColor: `rgba(246, 246, 246, 1)`,  
  boxShadow: `0px 4px 16px rgba(0, 0, 0, 0.15)`,  
  borderRadius: `32px`,  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `column`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `20px 52px`,  
  boxSizing: `border-box`,  
}));
  
const TempuraSwapMain1 = styled("div")(({ theme }) =>({  
  backgroundColor: `rgba(217, 217, 217, 1)`,  
  boxShadow: `0px 4px 16px rgba(0, 0, 0, 0.15)`,  
  borderRadius: `8px`,  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `center`,  
  alignItems: `center`,  
  padding: `10px 0px`,  
  boxSizing: `border-box`,  
  height: `32px`,  
  width: `585px`,  
  margin: `0px`,  
}));
  
const TempuraSwapMain2 = styled("div")(({ theme }) =>({  
  backgroundColor: `rgba(255, 153, 34, 1)`,  
  borderRadius: `8px`,  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `center`,  
  alignItems: `center`,  
  padding: `10px 0px`,  
  boxSizing: `border-box`,  
  width: `288px`,  
  height: `32px`,  
  margin: `0px`,  
}));
  
const Swap2 = styled("div")(({ theme }) =>({  
  textAlign: `left`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(255, 255, 255, 1)`,  
  fontStyle: `normal`,  
  fontWeight: `700`,  
  fontSize: `16px`,  
  letterSpacing: `0px`,  
  textDecoration: `none`,  
  textTransform: `none`,  
  margin: `0px`,  
}));
  
const TempuraSwapMain3 = styled("div")({  
  backgroundColor: `rgba(217, 217, 217, 1)`,  
  borderRadius: `64px`,  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `center`,  
  alignItems: `center`,  
  padding: `10px 0px`,  
  boxSizing: `border-box`,  
  width: `288px`,  
  height: `32px`,  
  margin: `0px 0px 0px 10px`,  
});
  
const Limit = styled("div")(({ theme }) =>({  
  textAlign: `left`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(134, 134, 134, 1)`,  
  fontStyle: `normal`,  
  fontWeight: `700`,  
  fontSize: `16px`,  
  letterSpacing: `0px`,  
  textDecoration: `none`,  
  textTransform: `none`,  
  margin: `0px`,  
}));
  
const Group1008 = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  height: `34px`,  
  width: `585px`,  
  margin: `24px 0px 0px 0px`,  
});
  
const Balance0 = styled("div")(({ theme }) =>({  
  textAlign: `left`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(35, 35, 35, 1)`,  
  fontStyle: `normal`,  

  fontWeight: `600`,  
  fontSize: `12px`,  
  letterSpacing: `0px`,  
  textDecoration: `none`,  
  lineHeight: `24px`,  
  textTransform: `none`,  
  position: `absolute`,  
  left: `524px`,  
  top: `10px`,  
}));
  
const Balance10000 = styled("div")(({ theme }) =>({  
  textAlign: `left`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(35, 35, 35, 1)`,  
  fontStyle: `normal`,   
  fontWeight: `600`,  
  fontSize: `12px`,  
  letterSpacing: `0px`,  
  textDecoration: `none`,  
  lineHeight: `24px`,  
  textTransform: `none`,  
  position: `absolute`,  
  left: `151px`,  
  top: `10px`,  
}));
  
const Token1 = styled("div")(({ theme }) =>({  
  backgroundColor: `rgba(255, 255, 255, 1)`,  
  boxShadow: `0px 4px 16px rgba(0, 0, 0, 0.15)`,  
  borderRadius: `32px`,  
  display: `flex`,  
  position: `absolute`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `center`,  
  alignItems: `center`,  
  padding: `5px 8px`,  
  boxSizing: `border-box`,  
  left: `0px`,  
  top: `0px`,  
}));
  
const Group1056 = styled("div")({  
  height: `24px`,  
  width: `24px`,  
  objectFit: `cover`,  
  margin: `0px`,  
});
  
const Token2 = styled(Token)(({ theme }) =>({  
  width: `24px`,  
  height: `24px`,  
  position: `absolute`,  
  left: `0px`,  
  top: `0px`,  
}));
  
const Bnto = styled("div")(({ theme }) =>({  
  textAlign: `left`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(35, 35, 35, 1)`,  
  fontStyle: `normal`,  
  fontWeight: `700`,  
  fontSize: `16px`,  
  letterSpacing: `0px`,  
  textDecoration: `none`,  
  lineHeight: `16.880184173583984px`,  
  textTransform: `none`,  
  margin: `0px 0px 0px 8px`,  
}));
  
const Group979 = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  width: `16px`,  
  height: `16px`,  
  margin: `0px 0px 0px 8px`,  
});
  
const KeyboardArrowDown = styled("div")({  
  borderRadius: `32px`,  
  display: `flex`,  
  position: `absolute`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  width: `16px`,  
  height: `16px`,  
  left: `0px`,  
  top: `0px`,  
  overflow: `hidden`,  
});
  
const Vector = styled("img")({  
  height: `16px`,  
  width: `16px`,  
  position: `absolute`,  
  left: `0px`,  
  top: `0px`,  
});
  
const Vector1 = styled("img")({  
  height: `9px`,  
  width: `14px`,  
  position: `absolute`,  
  left: `1px`,  
  top: `4px`,  
});
  
const Token3 = styled("div")(({ theme }) =>({  
  backgroundColor: `rgba(255, 255, 255, 1)`,  
  boxShadow: `0px 4px 16px rgba(0, 0, 0, 0.15)`,  
  borderRadius: `32px`,  
  display: `flex`,  
  position: `absolute`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `center`,  
  alignItems: `center`,  
  padding: `5px 8px`,  
  boxSizing: `border-box`,  
  left: `343px`,  
  top: `0px`,  
}));
  
const Image93 = styled("img")({  
  height: `24px`,  
  width: `24px`,  
  objectFit: `cover`,  
  margin: `0px`,  
});
  
const Usdc = styled("div")(({ theme }) =>({  
  textAlign: `left`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(35, 35, 35, 1)`,  
  fontStyle: `normal`,   
  fontWeight: `700`,  
  fontSize: `16px`,  
  letterSpacing: `0px`,  
  textDecoration: `none`,  
  lineHeight: `16.880184173583984px`,  
  textTransform: `none`,  
  margin: `0px 0px 0px 8px`,  
}));
  
const Group9791 = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  width: `16px`,  
  height: `16px`,  
  margin: `0px 0px 0px 8px`,  
});
  
const KeyboardArrowDown1 = styled("div")({  
  borderRadius: `32px`,  
  display: `flex`,  
  position: `absolute`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  width: `16px`,  
  height: `16px`,  
  left: `0px`,  
  top: `0px`,  
  overflow: `hidden`,  
});
  
const Vector2 = styled("img")({  
  height: `16px`,  
  width: `16px`,  
  position: `absolute`,  
  left: `0px`,  
  top: `0px`,  
});
  
const Vector3 = styled("img")({  
  height: `9px`,  
  width: `14px`,  
  position: `absolute`,  
  left: `1px`,  
  top: `4px`,  
});
  
const Group1009 = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  height: `46px`,  
  width: `585px`,  
  margin: `24px 0px 0px 0px`,  
});
  
const Frame7668 = styled("div")({  
  backgroundColor: `rgba(255, 255, 255, 1)`,  
  border: `2px solid rgba(255, 153, 34, 1)`,  
  boxSizing: `border-box`,  
  borderRadius: `8px`,  
  display: `flex`,  
  position: `absolute`,  
  isolation: `isolate`,  
  flexDirection: `column`,  
  justifyContent: `center`,  
  alignItems: `flex-end`,  
  padding: `0px 16px 0px 0px`,  
  width: `242px`,  
  height: `46px`,  
  left: `343px`,  
  top: `0px`,  
});
  
const Q00 = styled("div")({  
  textAlign: `left`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(153, 153, 153, 1)`,  
  fontStyle: `normal`,  
  fontWeight: `700`,  
  fontSize: `16px`,  
  letterSpacing: `0px`,  
  textDecoration: `none`,  
  lineHeight: `24px`,  
  textTransform: `none`,  
  margin: `0px`,  
});
  
const Frame7669 = styled("div")({  
  backgroundColor: `rgba(255, 255, 255, 1)`,  
  border: `2px solid rgba(255, 153, 34, 1)`,  
  boxSizing: `border-box`,  
  borderRadius: `8px`,  
  display: `flex`,  
  position: `absolute`,  
  isolation: `isolate`,  
  flexDirection: `column`,  
  justifyContent: `center`,  
  alignItems: `flex-end`,  
  padding: `0px 16px 0px 0px`,  
  width: `242px`,  
  height: `46px`,  
  left: `0px`,  
  top: `0px`,  
});
  
const Q001 = styled("div")({  
  textAlign: `left`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(153, 153, 153, 1)`,  
  fontStyle: `normal`,  
  fontWeight: `700`,  
  fontSize: `16px`,  
  letterSpacing: `0px`,  
  textDecoration: `none`,  
  lineHeight: `24px`,  
  textTransform: `none`,  
  margin: `0px`,  
});
  
const Frame7667 = styled("div")(({ theme }) =>({  
  boxShadow: `0px 4px 16px rgba(0, 0, 0, 0.15)`,  
  borderRadius: `64px`,  
  display: `flex`,  
  position: `absolute`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  width: `40px`,  
  height: `40px`,  
  left: `273px`,  
  top: `5px`,  
}));
  
const Subtract = styled("img")({  
  height: `40px`,  
  width: `40px`,  
  position: `absolute`,  
  left: `0px`,  
  top: `0px`,  
});
  
const Subtract1 = styled("img")({  
  height: `40px`,  
  width: `40px`,  
  position: `absolute`,  
  left: `0px`,  
  top: `0px`,  
});
  
const Group1010 = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  height: `24px`,  
  width: `242px`,  
  margin: `24px 0px 0px 0px`,  
});
  
const Group1007 = styled("div")({  
  display: `flex`,  
  position: `absolute`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  width: `242px`,  
  height: `24px`,  
  left: `0px`,  
  top: `0px`,  
});
  
const Frame7673 = styled("div")({  
  opacity: `0.5`,  
  border: `2px solid rgba(255, 153, 34, 1)`,  
  boxSizing: `border-box`,  
  borderRadius: `8px`,  
  display: `flex`,  
  position: `absolute`,  
  isolation: `isolate`,  
  flexDirection: `column`,  
  justifyContent: `center`,  
  alignItems: `center`,  
  padding: `0px`,  
  width: `55px`,  
  height: `24px`,  
  left: `187px`,  
  top: `0px`,  
});
  
const Max = styled("div")(({ theme }) =>({  
  textAlign: `left`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(255, 153, 34, 1)`,  
  fontStyle: `normal`,   
  fontWeight: `700`,  
  fontSize: `14px`,  
  letterSpacing: `0px`,  
  textDecoration: `none`,  
  lineHeight: `24px`,  
  textTransform: `none`,  
  margin: `0px`,  
}));
  
const Frame7670 = styled("div")(({ theme }) =>({  
  backgroundColor: `rgba(255, 153, 34, 1)`,  
  borderRadius: `8px`,  
  display: `flex`,  
  position: `absolute`,  
  isolation: `isolate`,  
  flexDirection: `column`,  
  justifyContent: `center`,  
  alignItems: `center`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  width: `55px`,  
  height: `24px`,  
  left: `0px`,  
  top: `0px`,  
}));
  
const Q25 = styled("div")({  
  textAlign: `left`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(255, 255, 255, 1)`,  
  fontStyle: `normal`,  
  fontWeight: `700`,  
  fontSize: `14px`,  
  letterSpacing: `0px`,  
  textDecoration: `none`,  
  lineHeight: `24px`,  
  textTransform: `none`,  
  margin: `0px`,  
});
  
const Frame7671 = styled("div")({  
  opacity: `0.5`,  
  border: `2px solid rgba(255, 153, 34, 1)`,  
  boxSizing: `border-box`,  
  borderRadius: `8px`,  
  display: `flex`,  
  position: `absolute`,  
  isolation: `isolate`,  
  flexDirection: `column`,  
  justifyContent: `center`,  
  alignItems: `center`,  
  padding: `0px`,  
  width: `55px`,  
  height: `24px`,  
  left: `63px`,  
  top: `0px`,  
});
  
const Q50 = styled("div")(({ theme }) =>({  
  textAlign: `left`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(255, 153, 34, 1)`,  
  fontStyle: `normal`,    
  fontWeight: `700`,  
  fontSize: `14px`,  
  letterSpacing: `0px`,  
  textDecoration: `none`,  
  lineHeight: `24px`,  
  textTransform: `none`,  
  margin: `0px`,  
}));
  
const Frame7672 = styled("div")({  
  opacity: `0.5`,  
  border: `2px solid rgba(255, 153, 34, 1)`,  
  boxSizing: `border-box`,  
  borderRadius: `8px`,  
  display: `flex`,  
  position: `absolute`,  
  isolation: `isolate`,  
  flexDirection: `column`,  
  justifyContent: `center`,  
  alignItems: `center`,  
  padding: `0px`,  
  width: `55px`,  
  height: `24px`,  
  left: `126px`,  
  top: `0px`,  
});
  
const Q75 = styled("div")(({ theme }) =>({  
  textAlign: `left`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(255, 153, 34, 1)`,  
  fontStyle: `normal`,  
  fontWeight: `700`,  
  fontSize: `14px`,  
  letterSpacing: `0px`,  
  textDecoration: `none`,  
  lineHeight: `24px`,  
  textTransform: `none`,  
  margin: `0px`,  
}));
  
const Group1011 = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  height: `41px`,  
  width: `585px`,  
  margin: `24px 0px 0px 0px`,  
});
  
const ButtonMain = styled("div")(({ theme }) =>({  
  backgroundColor: `rgba(192, 192, 192, 1)`,  
  boxShadow: `0px 4px 16px rgba(0, 0, 0, 0.15)`,  
  borderRadius: `8px`,  
  display: `flex`,  
  position: `absolute`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `center`,  
  alignItems: `center`,  
  padding: `10.5px 21px`,  
  boxSizing: `border-box`,  
  width: `585px`,  
  left: `0px`,  
  top: `0px`,  
}));
  
const ButtonTitle4 = styled("div")(({ theme }) =>({  
  textAlign: `center`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(255, 255, 255, 1)`,  
  fontStyle: `normal`,  
  fontWeight: `700`,  
  fontSize: `16px`,  
  letterSpacing: `0px`,  
  textDecoration: `none`,  
  lineHeight: `20px`,  
  textTransform: `none`,  
  margin: `0px`,  
}));
  
const Footer1 = styled(Footer)(({ theme }) =>({  
  width: `1920px`,  
  position: `absolute`,  
  left: `0px`,  
  top: `649px`,  
}));
  
const TopNavigation1 = styled(TopNavigation)(({ theme }) =>({  
  width: `1920px`,  
  height: `65.9px`,  
  position: `absolute`,  
  left: `0px`,  
  top: `0px`,  
}));
 
function Swap(props) {
  return (
    <Swap1 className={props.className} >
      <Helmet>
        <title>Swap</title>
      </Helmet>
      <Frame7675 >
        <Trade >
          {`Trade`}
            </Trade>
        <Tempura3DIllustratio  src={Tempura3DIllustratioImage} alt={"Tempura 3D Illustration"}/>
      </Frame7675>
      <Section4 >
        <Graph >
          <Group1004 >
            <Group1012 >
              <Q7210UsdcBnto0824135 >
                <Q7210UsdcBnto0824135Span1  >{`72.10 `}</Q7210UsdcBnto0824135Span1>
                <Q7210UsdcBnto0824135Span2  >{`USDC/BNTO `}</Q7210UsdcBnto0824135Span2>
                <Q7210UsdcBnto0824135Span3  >{`+0.824 (1.35%)`}</Q7210UsdcBnto0824135Span3>
              </Q7210UsdcBnto0824135>
              <Frame7674 >
                <Group1000 >
                  <Rectangle7 >
                  </Rectangle7>
                  <ButtonTitle >
                    {`24H`}
                      </ButtonTitle>
                </Group1000>
                <Group1001 >
                  <Rectangle71 >
                  </Rectangle71>
                  <ButtonTitle1 >
                    {`1W`}
                      </ButtonTitle1>
                </Group1001>
                <Group1002 >
                  <Rectangle72 >
                  </Rectangle72>
                  <ButtonTitle2 >
                    {`1M`}
                      </ButtonTitle2>
                </Group1002>
                <Group1003 >
                  <Rectangle73 >
                  </Rectangle73>
                  <ButtonTitle3 >
                    {`1Y`}
                      </ButtonTitle3>
                </Group1003>
              </Frame7674>
            </Group1012>
          </Group1004>
          <Group1014 >
            <Group1013 >
              <Q1900 >
                {`19:00`}
                  </Q1900>
              <Q2000 >
                {`20:00`}
                  </Q2000>
              <Graph1  src={Graph1Image} alt={"Graph"}/>
              <Q2100 >
                {`21:00`}
                  </Q2100>
              <Q2200 >
                {`22:00`}
                  </Q2200>
              <Q2300 >
                {`23:00`}
                  </Q2300>
              <Q0000 >
                {`00:00`}
                  </Q0000>
              <Q0100 >
                {`01:00`}
                  </Q0100>
              <Q0200 >
                {`02:00`}
                  </Q0200>
            </Group1013>
            <Oct1520220834Pm >
              {`Oct. 15, 2022, 08:34PM`}
                </Oct1520220834Pm>
          </Group1014>
        </Graph>
        <TempuraSwapMain >
          <TempuraSwapMain1 >
            <TempuraSwapMain2 >
              <Swap2 >
                {`Swap`}
                  </Swap2>
            </TempuraSwapMain2>
            <TempuraSwapMain3 >
              <Limit >
                {`Limit`}
                  </Limit>
            </TempuraSwapMain3>
          </TempuraSwapMain1>
          <Group1008 >
            <Balance0 >
              {`Balance: 0`}
                </Balance0>
            <Balance10000 >
              {`Balance: 10000`}
                </Balance10000>
            <Token1 >
            <Image93  src={Ellipse2Image} alt={"image 93"}/>
              <Bnto >
                {`BNTO`}
                  </Bnto>
              <Group9791 >
                <KeyboardArrowDown1 >
                  <Vector2  src={Vector2Image} alt={"Vector"}/>
                  <Vector3  src={Vector3Image} alt={"Vector"}/>
                </KeyboardArrowDown1>
              </Group9791>
            </Token1>
            <Token3 >
              <Image93  src={Image93Image} alt={"image 93"}/>
              <Usdc >
                {`USDC`}
                  </Usdc>
              <Group9791 >
                <KeyboardArrowDown1 >
                  <Vector2  src={Vector2Image} alt={"Vector"}/>
                  <Vector3  src={Vector3Image} alt={"Vector"}/>
                </KeyboardArrowDown1>
              </Group9791>
            </Token3>
          </Group1008>
          <Group1009 >
            <Frame7668 >
              <Q00 >
                {`0.0`}
                  </Q00>
            </Frame7668>
            <Frame7669 >
              <Q001 >
                {`0.0`}
                  </Q001>
            </Frame7669>
            <Frame7667 >
              <Subtract  src={SubtractImage} alt={"Subtract"}/>
              <Subtract1  src={Subtract1Image} alt={"Subtract"}/>
            </Frame7667>
          </Group1009>
          <Group1010 >
            <Group1007 >
              <Frame7673 >
                <Max >
                  {`MAX`}
                    </Max>
              </Frame7673>
              <Frame7670 >
                <Q25 >
                  {`25%`}
                    </Q25>
              </Frame7670>
              <Frame7671 >
                <Q50 >
                  {`50%`}
                    </Q50>
              </Frame7671>
              <Frame7672 >
                <Q75 >
                  {`75%`}
                    </Q75>
              </Frame7672>
            </Group1007>
          </Group1010>
          <Group1011 >
            <ButtonMain >
              <ButtonTitle4 >
                {`Please Enter Amount`}
                  </ButtonTitle4>
            </ButtonMain>
          </Group1011>
        </TempuraSwapMain>
      </Section4>
      <Footer1   />
      <TopNavigation1   />
    </Swap1>
  );
}

export default Swap;
