/**********************************************************************
*
*   Component generated by Quest
*
*   WARNING: By editing this component by hand, you will lose the ability to regenerate the code without conflicts. 
*   To preseve that abilty, always export from Quest to regenerate this file.
*   To setup props, bindings and actions, use the Quest editor
*   Code Logic goes in the hook associated with this component
*
*   For help and further details refer to: https://www.quest.ai/docs
*
*
**********************************************************************/

import JapaneseTea3DIllustrImage from 'src/assets/images/Component1_Japanese_Tea_3D_Illustration_1.png';
import { styled } from '@mui/material/styles';
import { autocompleteClasses } from '@mui/material';
import Token from 'src/components/Token/Token';
import Footer from 'src/components/Footer/Footer';
import TopNavigation from 'src/components/TopNavigation/TopNavigation';
 
const Component11 = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  width: "100%",  
  height: `655px`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  margin: 'auto'
});
  
const Frame7678 = styled("div")({  
  background: `linear-gradient(180deg, rgba(0, 187, 30, 1) -3.0616171314629196e-15%, rgba(0, 157, 25, 1) 99.99999999999999%)`,  
  display: `flex`,  
  position: `absolute`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `space-between`,  
  alignItems: `center`,  
  padding: `19px 160px`,  
  boxSizing: `border-box`,  
  width: `1920px`,  
  height: `120px`,  
  left: `0px`,  
  top: `0px`,  
  overflow: `hidden`,  
});
  
const Liquidity = styled("div")({  
  textAlign: `left`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(255, 255, 255, 1)`,  
  fontStyle: `normal`,  
  fontWeight: `700`,  
  fontSize: `48px`,  
  letterSpacing: `0px`,  
  textDecoration: `none`,  
  lineHeight: `24px`,  
  textTransform: `none`,  
});
  
const JapaneseTea3DIllustr = styled("img")({  
  height: `450px`,  
  width: `450px`,  
  objectFit: `cover`,  
});
  
const Section5 = styled("div")({  
  background: `linear-gradient(180deg, rgba(255, 193, 119, 1) 2.6856137439608534%, rgba(255, 236, 214, 1) 70.22814154624938%)`,  
  display: `flex`,  
  position: `absolute`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `space-between`,  
  alignItems: `center`,  
  padding: `72px 160px`,  
  boxSizing: `border-box`,  
  width: `1920px`,  
  left: `0px`,  
  top: `120px`,  
  margin: 'auto'
});
  
const TempuraSwapMain = styled("div")(({ theme }) =>({  
  backgroundColor: `rgba(246, 246, 246, 1)`,  
  boxShadow: `0px 4px 16px rgba(0, 0, 0, 0.15)`,  
  borderRadius: `32px`,  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `column`,  
  justifyContent: `flex-start`,  
  alignItems: `center`,  
  padding: `20px 52px`,  
  boxSizing: `border-box`,  
  width: `696px`,  
}));
  
const Liquidity1 = styled("div")(({ theme }) =>({  
  textAlign: `left`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(35, 35, 35, 1)`,  
  fontStyle: `normal`,   
  fontWeight: `800`,  
  fontSize: `32px`,  
  letterSpacing: `0px`,  
  textDecoration: `none`,  
  lineHeight: `36px`,  
  textTransform: `none`,  
  margin: `0px`,  
}));
  
const Group1069 = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  height: `48px`,  
  width: `275px`,  
  margin: 'auto'
});
  
const YourLiquidityRemoveLSpan1 = styled("span")({  
  whiteSpace: `pre-wrap`,  
  color: `rgba(35, 35, 35, 1)`,  
  fontStyle: `normal`,  
  fontWeight: `900`,  
  fontSize: `16px`,  
  letterSpacing: `0px`,  
  textDecoration: `none`,  
  lineHeight: `24px`,  
  textTransform: `none`,  
});
  
const YourLiquidityRemoveLSpan2 = styled("span")({  
  whiteSpace: `pre-wrap`,  
  color: `rgba(134, 134, 134, 1)`,  
  fontStyle: `normal`,   
  fontWeight: `500`,  
  fontSize: `16px`,  
  letterSpacing: `0px`,  
  textDecoration: `none`,  
  lineHeight: `24px`,  
  textTransform: `none`,  
});
  
const YourLiquidityRemoveL = styled("div")({  
  textAlign: `center`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(0, 0, 0, 1)`,  
  fontStyle: `normal`,   
  fontWeight: `400`,  
  fontSize: `16px`,  
  letterSpacing: `0px`,  
  textDecoration: `none`,  
  lineHeight: `24px`,  
  textTransform: `none`,  
  position: `absolute`,  
  left: `0px`,  
  top: `0px`,  
});
  
const Frame7685 = styled("div")({  
  backgroundColor: `rgba(217, 217, 217, 1)`,  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `center`,  
  alignItems: `center`,  
  padding: `0px 279px`,  
  boxSizing: `border-box`,  
  height: `154px`,  
  margin: `24px 0px 0px 0px`,  
});
  
const NoLiquidityFound = styled("div")(({ theme }) =>({  
  textAlign: `center`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(134, 134, 134, 1)`,  
  fontStyle: `normal`,   
  fontWeight: `900`,  
  fontSize: `16px`,  
  letterSpacing: `0px`,  
  textDecoration: `none`,  
  lineHeight: `24px`,  
  textTransform: `none`,  
  margin: `0px`,  
}));
  
const Group1011 = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  height: `41px`,  
  width: `585px`,  
  margin: `24px 0px 0px 0px`,  
});
  
const ButtonMain = styled("div")(({ theme }) =>({  
  backgroundColor: `rgba(4, 0, 182, 1)`,  
  boxShadow: `0px 4px 16px rgba(0, 0, 0, 0.15)`,  
  borderRadius: `8px`,  
  display: `flex`,  
  position: `absolute`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `center`,  
  alignItems: `center`,  
  padding: `10.5px 21px`,  
  boxSizing: `border-box`,  
  width: `585px`,  
  left: `0px`,  
  top: `0px`,  
}));
  
const ButtonTitle = styled("div")(({ theme }) =>({  
  textAlign: `center`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(255, 255, 255, 1)`,  
  fontStyle: `normal`,  
  fontWeight: `700`,  
  fontSize: `16px`,  
  letterSpacing: `0px`,  
  textDecoration: `none`,  
  lineHeight: `20px`,  
  textTransform: `none`,  
  margin: `0px`,  
}));
 
function Component1(props) {
  return (
    <Component11  className={props.className}   >
      <Frame7678 >
        <Liquidity >
          {`Liquidity`}
            </Liquidity>
        <JapaneseTea3DIllustr  src={JapaneseTea3DIllustrImage} alt={"Japanese Tea 3D Illustration 1"}/>
      </Frame7678>
      <Section5>
        <TempuraSwapMain style={{ margin: 'auto'}} >
          <Liquidity1 >
            {`Liquidity`}
              </Liquidity1>
          <Group1069 >
            <YourLiquidityRemoveL >
              <YourLiquidityRemoveLSpan1  >{`Your Liquidity
`}</YourLiquidityRemoveLSpan1>
              <YourLiquidityRemoveLSpan2  >{`Remove liquidity to receive token back`}</YourLiquidityRemoveLSpan2>
            </YourLiquidityRemoveL>
          </Group1069>
          <Frame7685 >
            <NoLiquidityFound >
              {`No Liquidity found.`}
                </NoLiquidityFound>
          </Frame7685>
          <Group1011 >
            <ButtonMain >
              <ButtonTitle >
                {`+ Add Liquidity`}
                  </ButtonTitle>
            </ButtonMain>
          </Group1011>
        </TempuraSwapMain>
      </Section5>

    </Component11>
  );
}

export default Component1;
