/**********************************************************************
*
*   Component generated by Quest
*
*   WARNING: By editing this component by hand, you will lose the ability to regenerate the code without conflicts. 
*   To preseve that abilty, always export from Quest to regenerate this file.
*   To setup props, bindings and actions, use the Quest editor
*   Code Logic goes in the hook associated with this component
*
*   For help and further details refer to: https://www.quest.ai/docs
*
*
**********************************************************************/

import G1757Image from 'src/assets/images/TopNavigation_g1757.png';
import UnionImage from 'src/assets/images/TopNavigation_Union.png';
import VectorImage from 'src/assets/images/TopNavigation_Vector_10.png';
import Vector1Image from 'src/assets/images/TopNavigation_Vector_9.png';
import Vector2Image from 'src/assets/images/TopNavigation_Vector_8.png';
import Vector3Image from 'src/assets/images/TopNavigation_Vector_7.png';
import Ellipse2Image from 'src/assets/images/TopNavigation_Ellipse_2_1.png';
import Ellipse21Image from 'src/assets/images/TopNavigation_Ellipse_2.png';
import Vector4Image from 'src/assets/images/TopNavigation_Vector_6.png';
import Vector5Image from 'src/assets/images/TopNavigation_Vector_5.png';
import Vector6Image from 'src/assets/images/TopNavigation_Vector_4.png';
import Vector7Image from 'src/assets/images/TopNavigation_Vector_3.png';
import Vector8Image from 'src/assets/images/TopNavigation_Vector_2.png';
import Vector9Image from 'src/assets/images/TopNavigation_Vector_1.png';
import Vector10Image from 'src/assets/images/TopNavigation_Vector.png';
import { styled } from '@mui/material/styles';
import Logo from 'src/components/Logo/Logo';
import Token from 'src/components/Token/Token';

 
const TopNavigation1 = styled("div")({  
  backgroundColor: `rgba(255, 255, 255, 1)`,  
  boxShadow: `0px 4px 16px rgba(0, 0, 0, 0.15)`,  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  width: "100%",  
  height: `76px`,  
  justifyContent: `space-between`,  
  alignItems: `center`,  
  padding: `10px 72px`,  
  boxSizing: `border-box`,  
});
  
const Group2 = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  width: `691.33px`,  
  height: `44.75px`,  
});
  
const Frame2 = styled("div")({  
  display: `flex`,  
  position: `absolute`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `space-between`,  
  alignItems: `center`,  
  padding: `0px 16px`,  
  boxSizing: `border-box`,  
  width: `464px`,  
  height: `33px`,  
  left: `227px`,  
  top: `12px`,  
});
  
const Group1121 = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  width: `86.94px`,  
  height: `56px`,  
});
  
const Trade = styled("div")(({ theme }) =>({  
  textAlign: `center`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(35, 35, 35, 1)`,  
  fontStyle: `normal`,  

  fontWeight: `500`,  
  fontSize: `16px`,  
  letterSpacing: `0px`,  
  textDecoration: `none`,  
  lineHeight: `56px`,  
  textTransform: `none`,  
  position: `absolute`,  
  left: `52px`,  
  top: `0px`,  
}));
  
const G1757 = styled("img")({  
  height: `38.5px`,  
  width: `28px`,  
  position: `absolute`,  
  left: `16px`,  
  top: `10px`,  
});
  
const Group1122 = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  width: `92.21px`,  
  height: `30.01px`,  
});
  
const Q1 = styled("div")({  
  display: `flex`,  
  position: `absolute`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  width: `16.83px`,  
  height: `30.01px`,  
  left: `0px`,  
  top: `0px`,  
});
  
const Union = styled("img")({  
  height: `30.01px`,  
  width: `16.83px`,  
  position: `absolute`,  
  left: `0px`,  
  top: `0px`,  
});
  
const Liquidity = styled("div")({  
  textAlign: `center`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(0, 0, 0, 1)`,  
  fontStyle: `normal`,  

  fontWeight: `500`,  
  fontSize: `16px`,  
  letterSpacing: `0px`,  
  textDecoration: `none`,  
  lineHeight: `56px`,  
  textTransform: `none`,  
  width: `66px`,  
  height: `25px`,  
  position: `absolute`,  
  left: `26px`,  
  bottom: `17px`,  
});
  
const Group1123 = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  width: `78.12px`,  
  height: `27.19px`,  
});
  
const Farm = styled("div")({  
  textAlign: `center`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(0, 0, 0, 1)`,  
  fontStyle: `normal`,  

  fontWeight: `500`,  
  fontSize: `16px`,  
  letterSpacing: `0px`,  
  textDecoration: `none`,  
  lineHeight: `56px`,  
  textTransform: `none`,  
  width: `39px`,  
  height: `25px`,  
  position: `absolute`,  
  left: `39px`,  
  bottom: `15px`,  
});
  
const Onigiri = styled("div")({  
  display: `flex`,  
  position: `absolute`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  width: `28.37px`,  
  height: `27.19px`,  
  left: `0px`,  
  top: `0px`,  
});
  
const Vector = styled("img")({  
  height: `27.19px`,  
  width: `28.37px`,  
  position: `absolute`,  
  left: `0px`,  
  top: `0px`,  
});
  
const Group1124 = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  width: `65.24px`,  
  height: `29.84px`,  
});
  
const Q11 = styled("div")({  
  display: `flex`,  
  position: `absolute`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  width: `18.22px`,  
  height: `29.84px`,  
  left: `0px`,  
  top: `0px`,  
});
  
const Vector1 = styled("img")({  
  height: `22.82px`,  
  width: `18.22px`,  
  position: `absolute`,  
  left: `0px`,  
  top: `7px`,  
});
  
const Vector2 = styled("img")({  
  height: `9.25px`,  
  width: `15.38px`,  
  position: `absolute`,  
  left: `1px`,  
  top: `0px`,  
});
  
const Vector3 = styled("img")({  
  height: `2.23px`,  
  width: `10.87px`,  
  position: `absolute`,  
  left: `4px`,  
  top: `11px`,  
});
  
const Pools = styled("div")({  
  textAlign: `center`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(0, 0, 0, 1)`,  
  fontStyle: `normal`,    
  fontWeight: `500`,  
  fontSize: `16px`,  
  letterSpacing: `0px`,  
  textDecoration: `none`,  
  lineHeight: `56px`,  
  textTransform: `none`,  
  width: `42px`,  
  height: `25px`,  
  position: `absolute`,  
  left: `28px`,  
  bottom: `15px`,  
});
  
const Group1119 = styled(Logo)(({ theme }) =>({  
  width: `142.39px`,  
  height: `44.75px`,  
  position: `absolute`,  
  left: `0px`,  
  top: `0px`,  
}));
  
const LeftNav = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `center`,  
  alignItems: `center`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
});
  
const Rate = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  width: `106px`,  
  height: `40px`,  
  margin: `0px`,  
});
  
const Ellipse2 = styled("img")({  
  height: `40px`,  
  width: `40px`,  
  position: `absolute`,  
  left: `0px`,  
  top: `0px`,  
});
  
const Group11191 = styled(Token)(({ theme }) =>({  
  width: `40px`,  
  height: `40px`,  
  position: `absolute`,  
  left: `1px`,  
  top: `0px`,  
}));
  
const Q050 = styled("div")({  
  textAlign: `center`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(0, 0, 0, 1)`,  
  fontStyle: `normal`,  
  fontWeight: `700`,  
  fontSize: `16px`,  
  letterSpacing: `0px`,  
  textDecoration: `none`,  
  lineHeight: `56px`,  
  textTransform: `none`,  
  width: `66px`,  
  height: `40px`,  
  position: `absolute`,  
  left: `40px`,  
  top: `0px`,  
});
  
const ConnectWallet = styled("div")(({ theme }) =>({  
  backgroundColor: `rgba(255, 255, 255, 1)`,  
  boxShadow: `0px 4px 16px rgba(0, 0, 0, 0.15)`,  
  border: `2px solid rgba(0, 0, 0, 1)`,  
  boxSizing: `border-box`,  
  borderRadius: `32px`,  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `center`,  
  padding: `10px 8px`,  
  height: `46px`,  
  margin: `0px 0px 0px 27px`,  
}));
  
const Group1132 = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  width: `94.65px`,  
  height: `56px`,  
  margin: `0px`,  
});
  
const Group1131 = styled("div")({  
  display: `flex`,  
  position: `absolute`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  width: `32px`,  
  height: `32px`,  
  left: `0px`,  
  top: `12px`,  
});
  
const Group1058 = styled("div")({  
  display: `flex`,  
  position: `absolute`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  width: `32px`,  
  height: `32px`,  
  left: `0px`,  
  top: `0px`,  
});
  
const Ellipse21 = styled("img")({  
  height: `32px`,  
  width: `32px`,  
  position: `absolute`,  
  left: `0px`,  
  top: `0px`,  
});
  
const Vector4 = styled("img")({  
  height: `26.57px`,  
  width: `26.54px`,  
  position: `absolute`,  
  left: `3px`,  
  top: `3px`,  
});
  
const Aptos = styled("div")(({ theme }) =>({  
  textAlign: `center`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(35, 35, 35, 1)`,  
  fontStyle: `normal`,   
  fontWeight: `700`,  
  fontSize: `16px`,  
  letterSpacing: `0px`,  
  textDecoration: `none`,  
  lineHeight: `56px`,  
  textTransform: `none`,  
  position: `absolute`,  
  left: `39px`,  
  top: `0px`,  
}));
  
const Group979 = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  width: `16px`,  
  height: `16px`,  
  margin: `0px 0px 0px 8px`,  
});
  
const KeyboardArrowDown = styled("div")({  
  borderRadius: `32px`,  
  display: `flex`,  
  position: `absolute`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  width: `16px`,  
  height: `16px`,  
  left: `0px`,  
  top: `0px`,  
  overflow: `hidden`,  
});
  
const Vector5 = styled("img")({  
  height: `16px`,  
  width: `16px`,  
  position: `absolute`,  
  left: `0px`,  
  top: `0px`,  
});
  
const Vector6 = styled("img")({  
  height: `9px`,  
  width: `14px`,  
  position: `absolute`,  
  left: `1px`,  
  top: `4px`,  
});
  
const ConnectWallet1 = styled("div")({  
  boxShadow: `0px 4px 16px rgba(0, 0, 0, 0.15)`,  
  border: `2px solid rgba(0, 0, 0, 1)`,  
  boxSizing: `border-box`,  
  borderRadius: `32px`,  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `center`,  
  alignItems: `center`,  
  padding: `10px`,  
  width: `200px`,  
  height: `46px`,  
  margin: `0px 0px 0px 27px`,  
});
  
const Group1133 = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  width: `145.84px`,  
  height: `56px`,  
  margin: `0px`,  
});
  
const Group = styled("div")({  
  display: `flex`,  
  position: `absolute`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  width: `16px`,  
  height: `16px`,  
  left: `0px`,  
  top: `21px`,  
});
  
const Vector7 = styled("img")({  
  height: `16px`,  
  width: `15px`,  
  position: `absolute`,  
  left: `0px`,  
  top: `0px`,  
});
  
const Vector8 = styled("img")({  
  height: `4px`,  
  width: `6px`,  
  position: `absolute`,  
  left: `10px`,  
  top: `8px`,  
});
  
const ConnectWallet2 = styled("div")(({ theme }) =>({  
  textAlign: `center`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(35, 35, 35, 1)`,  
  fontStyle: `normal`,   
  fontWeight: `700`,  
  fontSize: `16px`,  
  letterSpacing: `0px`,  
  textDecoration: `none`,  
  lineHeight: `56px`,  
  textTransform: `none`,  
  position: `absolute`,  
  left: `25px`,  
  top: `0px`,  
}));
  
const Settings = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  width: `36px`,  
  height: `36px`,  
  margin: `0px 0px 0px 27px`,  
  overflow: `hidden`,  
});
  
const Group1 = styled("div")({  
  display: `flex`,  
  position: `absolute`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  width: `40px`,  
  height: `40px`,  
  left: `0px`,  
  top: `0px`,  
});
  
const Vector9 = styled("img")({  
  height: `40px`,  
  width: `40px`,  
  position: `absolute`,  
  left: `0px`,  
  top: `0px`,  
});
  
const Vector10 = styled("img")({  
  height: `32px`,  
  width: `31.13px`,  
  position: `absolute`,  
  left: `4px`,  
  top: `4px`,  
});
 
function TopNavigation(props) {
  return (
    <TopNavigation1 className={props.className} >
      <Group2 >
        <Frame2 >
          <Group1121 >
            <Trade >
              {`Trade`}
                </Trade>
            <G1757  src={G1757Image} alt={"g1757"}/>
          </Group1121>
          <Group1122 >
            <Q1 >
              <Union  src={UnionImage} alt={"Union"}/>
            </Q1>
            <Liquidity >
              {`Liquidity`}
                </Liquidity>
          </Group1122>
          <Group1123 >
            <Farm >
              {`Farm`}
                </Farm>
            <Onigiri >
              <Vector  src={VectorImage} alt={"Vector"}/>
            </Onigiri>
          </Group1123>
          <Group1124 >
            <Q11 >
              <Vector1  src={Vector1Image} alt={"Vector"}/>
              <Vector2  src={Vector2Image} alt={"Vector"}/>
              <Vector3  src={Vector3Image} alt={"Vector"}/>
            </Q11>
            <Pools >
              {`Pools`}
                </Pools>
          </Group1124>
        </Frame2>
        <Group1119   />
      </Group2>
      <LeftNav >
        <Rate >
          <Ellipse2  src={Ellipse2Image} alt={"Ellipse 2"}/>
          <Group11191   />
          <Q050 >
            {`$0.50`}
              </Q050>
        </Rate>
        <ConnectWallet >
          <Group1132 >
            <Group1131 >
              <Group1058 >
                <Ellipse21  src={Ellipse21Image} alt={"Ellipse 2"}/>
              </Group1058>
              <Vector4  src={Vector4Image} alt={"Vector"}/>
            </Group1131>
            <Aptos >
              {`APTOS`}
                </Aptos>
          </Group1132>
          <Group979 >
            <KeyboardArrowDown >
              <Vector5  src={Vector5Image} alt={"Vector"}/>
              <Vector6  src={Vector6Image} alt={"Vector"}/>
            </KeyboardArrowDown>
          </Group979>
        </ConnectWallet>
        <ConnectWallet1 >
          <Group1133 >
            <Group >
              <Vector7  src={Vector7Image} alt={"Vector"}/>
              <Vector8  src={Vector8Image} alt={"Vector"}/>
            </Group>
            <ConnectWallet2 >
              {`Connect Wallet`}
                </ConnectWallet2>
          </Group1133>
        </ConnectWallet1>
        <Settings >
          <Group1 >
            <Vector9  src={Vector9Image} alt={"Vector"}/>
            <Vector10  src={Vector10Image} alt={"Vector"}/>
          </Group1>
        </Settings>
      </LeftNav>
    </TopNavigation1>
  );
}

export default TopNavigation;
