/**********************************************************************
*
*   Component generated by Quest
*
*   WARNING: By editing this component by hand, you will lose the ability to regenerate the code without conflicts. 
*   To preseve that abilty, always export from Quest to regenerate this file.
*   To setup props, bindings and actions, use the Quest editor
*   Code Logic goes in the hook associated with this component
*
*   For help and further details refer to: https://www.quest.ai/docs
*
*
**********************************************************************/

import VectorImage from 'src/assets/images/Footer_Vector_3.png';
import Vector1Image from 'src/assets/images/Footer_Vector_2.png';
import Vector2Image from 'src/assets/images/Footer_Vector_1.png';
import Vector3Image from 'src/assets/images/Footer_Vector.png';
import { styled } from '@mui/material/styles';
import Logo from 'src/components/Logo/Logo';

 
const Footer1 = styled("div")({  
  backgroundColor: `rgba(27, 28, 42, 1)`,  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `column`,  
  width: "100%",  
  justifyContent: `center`,  
  alignItems: `center`,  
  padding: `64px 160px`,  
  boxSizing: `border-box`,  
});
  
const Group1106 = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  height: `169.5px`,  
  width: `1629.73px`,  
  margin: `0px`,  
});
  
const Group989 = styled("div")({  
  display: `flex`,  
  position: `absolute`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  width: `198px`,  
  height: `151.01px`,  
  left: `0px`,  
  top: `18px`,  
});
  
const Group1119 = styled(Logo)(({ theme }) =>({  
  width: `197.4px`,  
  height: `62.04px`,  
  position: `absolute`,  
  left: `0px`,  
  top: `0px`,  
}));
  
const Copyright2022BentoSw = styled("div")({  
  textAlign: `left`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(192, 192, 192, 1)`,  
  fontStyle: `normal`,  
  fontWeight: `500`,  
  fontSize: `14px`,  
  letterSpacing: `0px`,  
  textDecoration: `none`,  
  lineHeight: `24px`,  
  textTransform: `none`,  
  position: `absolute`,  
  left: `6px`,  
  top: `72px`,  
  width: '200%'
});
  
const Frame7684 = styled("div")({  
  border: `1px solid rgba(156, 156, 156, 1)`,  
  boxSizing: `border-box`,  
  borderRadius: `32px`,  
  display: `flex`,  
  position: `absolute`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `center`,  
  alignItems: `center`,  
  padding: `4px 32px`,  
  width: `198px`,  
  left: `0px`,  
  top: `111px`,  
});
  
const AuditedBy = styled("div")({  
  textAlign: `center`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(192, 192, 192, 1)`,  
  fontStyle: `normal`,   
  fontWeight: `500`,  
  fontSize: `14px`,  
  letterSpacing: `0px`,  
  textDecoration: `none`,  
  lineHeight: `32px`,  
  textTransform: `none`,  
  margin: `0px`,  
});
  
const Group992 = styled("div")({  
  display: `flex`,  
  position: `absolute`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  width: `701px`,  
  height: `168px`,  
  left: `929px`,  
  top: `0px`,  
});
  
const Vector = styled("img")({  
  height: `18.24px`,  
  width: `18.24px`,  
  position: `absolute`,  
  left: `605px`,  
  top: `46px`,  
});
  
const Vector1 = styled("img")({  
  height: `18px`,  
  width: `18px`,  
  position: `absolute`,  
  left: `605px`,  
  top: `78px`,  
});
  
const Vector2 = styled("img")({  
  height: `18px`,  
  width: `16.24px`,  
  position: `absolute`,  
  left: `606px`,  
  top: `111px`,  
});
  
const Group = styled("div")({  
  display: `flex`,  
  position: `absolute`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  width: `18px`,  
  height: `18px`,  
  left: `605px`,  
  top: `142px`,  
});
  
const Vector3 = styled("img")({  
  height: `18px`,  
  width: `18px`,  
  position: `absolute`,  
  left: `0px`,  
  top: `0px`,  
});
  
const AboutContactUsBrandCSpan1 = styled("span")({  
  whiteSpace: `pre-wrap`,  
  color: `rgba(255, 255, 255, 1)`,  
  fontStyle: `normal`,   
  fontWeight: `900`,  
  fontSize: `16px`,  
  letterSpacing: `0.48px`,  
  textDecoration: `none`,  
  lineHeight: `32px`,  
  textTransform: `none`,  
});
  
const AboutContactUsBrandCSpan2 = styled("span")({  
  whiteSpace: `pre-wrap`,  
  color: `rgba(255, 255, 255, 1)`,  
  fontStyle: `normal`,  
  fontWeight: `400`,  
  fontSize: `16px`,  
  letterSpacing: `0.48px`,  
  textDecoration: `none`,  
  lineHeight: `40px`,  
  textTransform: `none`,  
});
  
const AboutContactUsBrandCSpan3 = styled("span")({  
  whiteSpace: `pre-wrap`,  
  color: `rgba(255, 255, 255, 1)`,  
  fontStyle: `normal`,  
  fontWeight: `400`,  
  fontSize: `16px`,  
  letterSpacing: `0.48px`,  
  textDecoration: `none`,  
  lineHeight: `24px`,  
  textTransform: `none`,  
});
  
const AboutContactUsBrandCSpan4 = styled("span")({  
  whiteSpace: `pre-wrap`,  
  color: `rgba(255, 255, 255, 1)`,  
  fontStyle: `normal`,  
  fontWeight: `400`,  
  fontSize: `16px`,  
  letterSpacing: `0.48px`,  
  textDecoration: `none`,  
  lineHeight: `32px`,  
  textTransform: `none`,  
});
  
const AboutContactUsBrandC = styled("div")({  
  textAlign: `left`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(255, 255, 255, 1)`,  
  fontStyle: `normal`,  
  fontWeight: `400`,  
  fontSize: `16px`,  
  letterSpacing: `0.48px`,  
  textDecoration: `none`,  
  textTransform: `none`,  
  width: `112px`,  
  height: `149px`,  
  position: `absolute`,  
  left: `0px`,  
  top: `0px`,  
});
  
const InformationNewsCustoSpan1 = styled("span")({  
  whiteSpace: `pre-wrap`,  
  color: `rgba(255, 255, 255, 1)`,  
  fontStyle: `normal`,   
  fontWeight: `800`,  
  fontSize: `16px`,  
  letterSpacing: `0.48px`,  
  textDecoration: `none`,  
  lineHeight: `32px`,  
  textTransform: `none`,  
});
  
const InformationNewsCustoSpan2 = styled("span")({  
  whiteSpace: `pre-wrap`,  
  color: `rgba(255, 255, 255, 1)`,  
  fontStyle: `normal`,  
  fontWeight: `400`,  
  fontSize: `16px`,  
  letterSpacing: `0.48px`,  
  textDecoration: `none`,  
  lineHeight: `40px`,  
  textTransform: `none`,  
});
  
const InformationNewsCustoSpan3 = styled("span")({  
  whiteSpace: `pre-wrap`,  
  color: `rgba(255, 255, 255, 1)`,  
  fontStyle: `normal`,   
  fontWeight: `400`,  
  fontSize: `16px`,  
  letterSpacing: `0.48px`,  
  textDecoration: `none`,  
  lineHeight: `32px`,  
  textTransform: `none`,  
});
  
const InformationNewsCusto = styled("div")({  
  textAlign: `left`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(255, 255, 255, 1)`,  
  fontStyle: `normal`,    
  fontWeight: `400`,  
  fontSize: `16px`,  
  letterSpacing: `0.48px`,  
  textDecoration: `none`,  
  textTransform: `none`,  
  position: `absolute`,  
  left: `196px`,  
  top: `0px`,  
});
  
const ParticipateVoteCollaSpan1 = styled("span")({  
  whiteSpace: `pre-wrap`,  
  color: `rgba(255, 255, 255, 1)`,  
  fontStyle: `normal`,   
  fontWeight: `800`,  
  fontSize: `16px`,  
  letterSpacing: `0.48px`,  
  textDecoration: `none`,  
  lineHeight: `32px`,  
  textTransform: `none`,  
});
  
const ParticipateVoteCollaSpan2 = styled("span")({  
  whiteSpace: `pre-wrap`,  
  color: `rgba(255, 255, 255, 1)`,  
  fontStyle: `normal`,   
  fontWeight: `400`,  
  fontSize: `16px`,  
  letterSpacing: `0.48px`,  
  textDecoration: `none`,  
  lineHeight: `40px`,  
  textTransform: `none`,  
});
  
const ParticipateVoteCollaSpan3 = styled("span")({  
  whiteSpace: `pre-wrap`,  
  color: `rgba(255, 255, 255, 1)`,  
  fontStyle: `normal`,   
  fontWeight: `400`,  
  fontSize: `16px`,  
  letterSpacing: `0.48px`,  
  textDecoration: `none`,  
  lineHeight: `24px`,  
  textTransform: `none`,  
});
  
const ParticipateVoteCollaSpan4 = styled("span")({  
  whiteSpace: `pre-wrap`,  
  color: `rgba(255, 255, 255, 1)`,  
  fontStyle: `normal`,   
  fontWeight: `400`,  
  fontSize: `16px`,  
  letterSpacing: `0.48px`,  
  textDecoration: `none`,  
  lineHeight: `32px`,  
  textTransform: `none`,  
});
  
const ParticipateVoteColla = styled("div")({  
  textAlign: `left`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(255, 255, 255, 1)`,  
  fontStyle: `normal`,  
  fontWeight: `400`,  
  fontSize: `16px`,  
  letterSpacing: `0.48px`,  
  textDecoration: `none`,  
  textTransform: `none`,  
  position: `absolute`,  
  left: `419px`,  
  top: `0px`,  
});
  
const Community = styled("div")({  
  textAlign: `left`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(255, 255, 255, 1)`,  
  fontStyle: `normal`,   
  fontWeight: `800`,  
  fontSize: `16px`,  
  letterSpacing: `0.48px`,  
  textDecoration: `none`,  
  lineHeight: `32px`,  
  textTransform: `none`,  
  position: `absolute`,  
  left: `605px`,  
  top: `0px`,  
});
  
const TwitterTelegramDisco = styled("div")({  
  textAlign: `left`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(255, 255, 255, 1)`,  
  fontStyle: `normal`,   
  fontWeight: `400`,  
  fontSize: `16px`,  
  letterSpacing: `0.48px`,  
  textDecoration: `none`,  
  lineHeight: `32px`,  
  textTransform: `none`,  
  position: `absolute`,  
  left: `631px`,  
  top: `40px`,  
});
 
function Footer(props) {
  return (
    <Footer1 className={props.className} >
      <Group1106 >
        <Group989 >
          <Group1119   />
          <Copyright2022BentoSw >
            {`Copyright © 2022 BentoSwap`}
              </Copyright2022BentoSw>
          <Frame7684 >
            <AuditedBy >
              {`Audited by _______`}
                </AuditedBy>
          </Frame7684>
        </Group989>
        <Group992 >
          <Vector  src={VectorImage} alt={"Vector"}/>
          <Vector1  src={Vector1Image} alt={"Vector"}/>
          <Vector2  src={Vector2Image} alt={"Vector"}/>
          <Group >
            <Vector3  src={Vector3Image} alt={"Vector"}/>
          </Group>
          <AboutContactUsBrandC >
            <AboutContactUsBrandCSpan1  >{`About
`}</AboutContactUsBrandCSpan1>
            <AboutContactUsBrandCSpan2  >{`Contact`}</AboutContactUsBrandCSpan2>
            <AboutContactUsBrandCSpan3  >{` Us
`}</AboutContactUsBrandCSpan3>
            <AboutContactUsBrandCSpan4  >{`Brand
Community
Whitepaper`}</AboutContactUsBrandCSpan4>
          </AboutContactUsBrandC>
          <InformationNewsCusto >
            <InformationNewsCustoSpan1  >{`Information
`}</InformationNewsCustoSpan1>
            <InformationNewsCustoSpan2  >{`News
`}</InformationNewsCustoSpan2>
            <InformationNewsCustoSpan3  >{`Customer Support
Troubleshooting
FAQs`}</InformationNewsCustoSpan3>
          </InformationNewsCusto>
          <ParticipateVoteColla >
            <ParticipateVoteCollaSpan1  >{`Participate
`}</ParticipateVoteCollaSpan1>
            <ParticipateVoteCollaSpan2  >{`Vote`}</ParticipateVoteCollaSpan2>
            <ParticipateVoteCollaSpan3  >{` 
`}</ParticipateVoteCollaSpan3>
            <ParticipateVoteCollaSpan4  >{`Collabration
Token Listing
Farm`}</ParticipateVoteCollaSpan4>
          </ParticipateVoteColla>
          <Community >
            {`Community
`}
              </Community>
          <TwitterTelegramDisco >
            {`Twitter 
Telegram
Discord
Medium`}
              </TwitterTelegramDisco>
        </Group992>
      </Group1106>
    </Footer1>
  );
}

export default Footer;
