/**********************************************************************
*
*   Component generated by Quest
*
*   WARNING: By editing this component by hand, you will lose the ability to regenerate the code without conflicts. 
*   To preseve that abilty, always export from Quest to regenerate this file.
*   To setup props, bindings and actions, use the Quest editor
*   Code Logic goes in the hook associated with this component
*
*   For help and further details refer to: https://www.quest.ai/docs
*
*
**********************************************************************/

import Ellipse2Image from 'src/assets/images/Token_Ellipse_2.png';
import UnionImage from 'src/assets/images/Token_Union.png';
import IntersectImage from 'src/assets/images/Token_Intersect.png';
import Ellipse233Image from 'src/assets/images/Token_Ellipse_233.png';
import Ellipse234Image from 'src/assets/images/Token_Ellipse_234.png';
import Vector9Image from 'src/assets/images/Token_Vector_9.png';
import Group16Image from 'src/assets/images/Token_Group_16.png';
import Vector4Image from 'src/assets/images/Token_Vector_4.png';
import Vector6Image from 'src/assets/images/Token_Vector_6.png';
import Vector5Image from 'src/assets/images/Token_Vector_5.png';
import Group1041Image from 'src/assets/images/Token_Group_1041.png';
import BentoImage from 'src/assets/images/Token_BENTO_4.png';
import Bento1Image from 'src/assets/images/Token_BENTO_3.png';
import Bento2Image from 'src/assets/images/Token_BENTO_2.png';
import Bento3Image from 'src/assets/images/Token_BENTO_1.png';
import Bento4Image from 'src/assets/images/Token_BENTO.png';
import { styled } from '@mui/material/styles';

 
const Token1 = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  width: "100%",  
  height: `46px`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
});
  
const Group1063 = styled("div")({  
  display: `flex`,  
  position: `absolute`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  width: `46px`,  
  height: `46px`,  
  left: `0px`,  
  top: `0px`,  
});
  
const Group1058 = styled("div")({  
  display: `flex`,  
  position: `absolute`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  width: `46px`,  
  height: `46px`,  
  left: `0px`,  
  top: `0px`,  
});
  
const Ellipse2 = styled("img")({  
  height: `46px`,  
  width: `46px`,  
  position: `absolute`,  
  left: `0px`,  
  top: `0px`,  
});
  
const Group1054 = styled("div")({  
  display: `flex`,  
  position: `absolute`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  width: `31px`,  
  height: `29.51px`,  
  left: `8px`,  
  top: `9px`,  
});
  
const Group1040 = styled("div")({  
  display: `flex`,  
  position: `absolute`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  width: `31px`,  
  height: `29.51px`,  
  left: `0px`,  
  top: `0px`,  
});
  
const Union = styled("img")({  
  height: `29.51px`,  
  width: `31px`,  
  position: `absolute`,  
  left: `0px`,  
  top: `0px`,  
});
  
const Intersect = styled("img")({  
  height: `6.29px`,  
  width: `30.87px`,  
  position: `absolute`,  
  left: `0px`,  
  top: `10px`,  
});
  
const Ellipse233 = styled("img")({  
  height: `2.99px`,  
  width: `2.99px`,  
  position: `absolute`,  
  left: `10px`,  
  top: `17px`,  
});
  
const Ellipse234 = styled("img")({  
  height: `2.99px`,  
  width: `2.99px`,  
  position: `absolute`,  
  left: `18px`,  
  top: `17px`,  
});
  
const Group17 = styled("div")({  
  boxShadow: `0px 0.3331972360610962px 1.3327889442443848px rgba(0, 0, 0, 0.15)`,  
  display: `flex`,  
  position: `absolute`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  width: `6.11px`,  
  height: `1.76px`,  
  left: `12px`,  
  top: `21px`,  
});
  
const Group15 = styled("div")({  
  display: `flex`,  
  position: `absolute`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  width: `3.05px`,  
  height: `1.76px`,  
  left: `3px`,  
  top: `0px`,  
});
  
const Group7 = styled("div")({  
  display: `flex`,  
  position: `absolute`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  width: `3.05px`,  
  height: `1.76px`,  
  left: `0px`,  
  top: `0px`,  
});
  
const Vector9 = styled("img")({  
  height: `1.76px`,  
  width: `3.05px`,  
  position: `absolute`,  
  left: `6px`,  
  top: `2px`,  
});
  
const Group16 = styled("img")({  
  height: `1.76px`,  
  width: `3.05px`,  
  position: `absolute`,  
  left: `6px`,  
  top: `2px`,  
});
  
const Group5 = styled("div")({  
  boxShadow: `0px 0.1374996155500412px 0.5499984622001648px rgba(0, 0, 0, 0.15)`,  
  display: `flex`,  
  position: `absolute`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  width: `2.66px`,  
  height: `3.44px`,  
  left: `22px`,  
  top: `23px`,  
});
  
const Vector4 = styled("img")({  
  height: `0px`,  
  width: `2.66px`,  
  position: `absolute`,  
  left: `0px`,  
  top: `-3px`,  
});
  
const Vector6 = styled("img")({  
  height: `0px`,  
  width: `2.66px`,  
  position: `absolute`,  
  left: `0px`,  
  top: `-2px`,  
});
  
const Vector5 = styled("img")({  
  height: `0px`,  
  width: `2.66px`,  
  position: `absolute`,  
  left: `5px`,  
  top: `0px`,  
});
  
const Group1041 = styled("img")({  
  height: `3.44px`,  
  width: `2.66px`,  
  position: `absolute`,  
  left: `11px`,  
  top: `26px`,  
});
  
const Rectangle11 = styled("div")({  
  backgroundColor: `rgba(0, 0, 0, 1)`,  
  borderRadius: `1px`,  
  width: `1.96px`,  
  height: `4.74px`,  
  position: `absolute`,  
  left: `23px`,  
  top: `13px`,  
});
  
const Rectangle12 = styled("div")({  
  backgroundColor: `rgba(0, 0, 0, 1)`,  
  borderRadius: `1px`,  
  width: `1.96px`,  
  height: `4.74px`,  
  position: `absolute`,  
  left: `25px`,  
  top: `13px`,  
});
  
const Rectangle13 = styled("div")({  
  backgroundColor: `rgba(0, 0, 0, 1)`,  
  borderRadius: `1px`,  
  width: `1.96px`,  
  height: `4.74px`,  
  position: `absolute`,  
  left: `20px`,  
  top: `13px`,  
});
  
const Group1064 = styled("div")({  
  display: `flex`,  
  position: `absolute`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  width: `12.84px`,  
  height: `2.1px`,  
  left: `17px`,  
  top: `20px`,  
});
  
const Bento = styled("img")({  
  height: `1.63px`,  
  width: `1.45px`,  
  position: `absolute`,  
  left: `0px`,  
  top: `0px`,  
});
  
const Bento1 = styled("img")({  
  height: `1.63px`,  
  width: `1.28px`,  
  position: `absolute`,  
  left: `3px`,  
  top: `0px`,  
});
  
const Bento2 = styled("img")({  
  height: `1.63px`,  
  width: `1.41px`,  
  position: `absolute`,  
  left: `6px`,  
  top: `0px`,  
});
  
const Bento3 = styled("img")({  
  height: `1.63px`,  
  width: `1.43px`,  
  position: `absolute`,  
  left: `8px`,  
  top: `0px`,  
});
  
const Bento4 = styled("img")({  
  height: `1.68px`,  
  width: `1.5px`,  
  position: `absolute`,  
  left: `11px`,  
  top: `0px`,  
});
 
function Token(props) {
  return (
    <Token1 className={props.className} >
      <Group1063 >
        <Group1058 >
          <Ellipse2  src={Ellipse2Image} alt={"Ellipse 2"}/>
          <Group1054 >
            <Group1040 >
              <Union  src={UnionImage} alt={"Union"}/>
              <Intersect  src={IntersectImage} alt={"Intersect"}/>
            </Group1040>
            <Ellipse233  src={Ellipse233Image} alt={"Ellipse 233"}/>
            <Ellipse234  src={Ellipse234Image} alt={"Ellipse 234"}/>
            <Group17 >
              <Group15 >
                <Group7 >
                  <Vector9  src={Vector9Image} alt={"Vector 9"}/>
                </Group7>
              </Group15>
              <Group16  src={Group16Image} alt={"Group 16"}/>
            </Group17>
            <Group5 >
              <Vector4  src={Vector4Image} alt={"Vector 4"}/>
              <Vector6  src={Vector6Image} alt={"Vector 6"}/>
              <Vector5  src={Vector5Image} alt={"Vector 5"}/>
            </Group5>
            <Group1041  src={Group1041Image} alt={"Group 1041"}/>
          </Group1054>
        </Group1058>
        <Rectangle11 >
        </Rectangle11>
        <Rectangle12 >
        </Rectangle12>
        <Rectangle13 >
        </Rectangle13>
      </Group1063>
      <Group1064 >
        <Bento  src={BentoImage} alt={"BENTO"}/>
        <Bento1  src={Bento1Image} alt={"BENTO"}/>
        <Bento2  src={Bento2Image} alt={"BENTO"}/>
        <Bento3  src={Bento3Image} alt={"BENTO"}/>
        <Bento4  src={Bento4Image} alt={"BENTO"}/>
      </Group1064>
    </Token1>
  );
}

export default Token;
